create table if not exists public.mail_delivery_jobs (
  id uuid not null default gen_random_uuid(),
  event_type character varying(100) not null default 'form_answer_notification'::character varying,
  provider character varying(50) null,
  status character varying(50) not null default 'pending'::character varying,
  form_id uuid null,
  answer_id uuid null,
  recipient_email text not null,
  subject text not null,
  payload jsonb not null default '{}'::jsonb,
  attempt_count integer not null default 0,
  last_error text null,
  provider_message_id text null,
  queued_by uuid null,
  last_attempt_at timestamp with time zone null,
  sent_at timestamp with time zone null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint mail_delivery_jobs_pkey primary key (id),
  constraint mail_delivery_jobs_status_check check (
    (status)::text = any (
      array['pending'::text, 'processing'::text, 'sent'::text, 'failed'::text]
    )
  ),
  constraint mail_delivery_jobs_provider_check check (
    provider is null or (provider)::text = any (
      array['smtp'::text, 'resend'::text]
    )
  ),
  constraint mail_delivery_jobs_payload_is_object check (jsonb_typeof(payload) = 'object'),
  constraint mail_delivery_jobs_form_id_fkey foreign key (form_id) references public.forms(id) on delete cascade,
  constraint mail_delivery_jobs_answer_id_fkey foreign key (answer_id) references public.forms_answers(id) on delete set null,
  constraint mail_delivery_jobs_queued_by_fkey foreign key (queued_by) references auth.users(id) on delete set null
) tablespace pg_default;

create index if not exists idx_mail_delivery_jobs_status_created_at on public.mail_delivery_jobs using btree (status, created_at desc) tablespace pg_default;
create index if not exists idx_mail_delivery_jobs_form_id_created_at on public.mail_delivery_jobs using btree (form_id, created_at desc) tablespace pg_default;
create index if not exists idx_mail_delivery_jobs_answer_id on public.mail_delivery_jobs using btree (answer_id) tablespace pg_default;
create index if not exists idx_mail_delivery_jobs_recipient_email on public.mail_delivery_jobs using btree (recipient_email) tablespace pg_default;

alter table public.mail_delivery_jobs enable row level security;

drop trigger if exists set_mail_delivery_jobs_updated_at on public.mail_delivery_jobs;
create trigger set_mail_delivery_jobs_updated_at
  before update on public.mail_delivery_jobs
  for each row
  execute function set_current_timestamp_updated_at();

drop policy if exists "admin_select_mail_delivery_jobs" on public.mail_delivery_jobs;
create policy "admin_select_mail_delivery_jobs"
  on public.mail_delivery_jobs
  for select
  to authenticated
  using (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  );

create table if not exists public.mail_delivery_events (
  id bigint generated by default as identity primary key,
  job_id uuid not null,
  event_type character varying(50) not null,
  message text null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  constraint mail_delivery_events_event_type_check check (
    (event_type)::text = any (
      array['queued'::text, 'testing'::text, 'sending'::text, 'sent'::text, 'failed'::text]
    )
  ),
  constraint mail_delivery_events_metadata_is_object check (jsonb_typeof(metadata) = 'object'),
  constraint mail_delivery_events_job_id_fkey foreign key (job_id) references public.mail_delivery_jobs(id) on delete cascade
) tablespace pg_default;

create index if not exists idx_mail_delivery_events_job_id_created_at on public.mail_delivery_events using btree (job_id, created_at desc) tablespace pg_default;
create index if not exists idx_mail_delivery_events_event_type on public.mail_delivery_events using btree (event_type) tablespace pg_default;

alter table public.mail_delivery_events enable row level security;

drop policy if exists "admin_select_mail_delivery_events" on public.mail_delivery_events;

create policy "admin_select_mail_delivery_events"
  on public.mail_delivery_events
  for select
  to authenticated
  using (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  );
