create table if not exists public.staff (
  id uuid primary key default gen_random_uuid(),
  account_user_id uuid null,
  display_name text not null,
  email text null,
  phone text null,
  avatar_url text null,
  job_title text null,
  status text not null default 'active',
  notes text null,
  profile jsonb not null default '{}'::jsonb,
  created_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint staff_account_user_id_key unique (account_user_id),
  constraint staff_display_name_check check (display_name <> ''::text),
  constraint staff_status_check check (status = any (array['active'::text, 'inactive'::text, 'archived'::text])),
  constraint staff_profile_is_object check (jsonb_typeof(profile) = 'object'),
  constraint staff_account_user_id_fkey foreign key (account_user_id) references public.user_profile (user_id) on delete set null,
  constraint staff_created_by_fkey foreign key (created_by) references public.user_profile (user_id) on delete set null
) tablespace pg_default;

create index if not exists idx_staff_display_name on public.staff using btree (display_name) tablespace pg_default;
create index if not exists idx_staff_status on public.staff using btree (status) tablespace pg_default;

create table if not exists public.staff_traits (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text null,
  description text null,
  metadata jsonb not null default '{}'::jsonb,
  category text null,
  is_active boolean not null default true,
  created_by uuid null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint staff_traits_name_key unique (name),
  constraint staff_traits_name_check check (name <> ''::text),
  constraint staff_traits_metadata_is_object check (jsonb_typeof(metadata) = 'object'),
  constraint staff_traits_created_by_fkey foreign key (created_by) references public.user_profile (user_id) on delete set null
) tablespace pg_default;

create index if not exists idx_staff_traits_slug on public.staff_traits using btree (slug) tablespace pg_default;
create index if not exists idx_staff_traits_category on public.staff_traits using btree (category) tablespace pg_default;

create table if not exists public.staff_trait_assignments (
  staff_id uuid not null,
  trait_id bigint not null,
  metadata jsonb not null default '{}'::jsonb,
  created_by uuid null,
  created_at timestamptz not null default now(),
  constraint staff_trait_assignments_pkey primary key (staff_id, trait_id),
  constraint staff_trait_assignments_metadata_is_object check (jsonb_typeof(metadata) = 'object'),
  constraint staff_trait_assignments_staff_id_fkey foreign key (staff_id) references public.staff (id) on delete cascade,
  constraint staff_trait_assignments_trait_id_fkey foreign key (trait_id) references public.staff_traits (id) on delete cascade,
  constraint staff_trait_assignments_created_by_fkey foreign key (created_by) references public.user_profile (user_id) on delete set null
) tablespace pg_default;

create index if not exists idx_staff_trait_assignments_trait_id on public.staff_trait_assignments using btree (trait_id) tablespace pg_default;

alter table public.staff enable row level security;
alter table public.staff_traits enable row level security;
alter table public.staff_trait_assignments enable row level security;

drop policy if exists "authenticated_select_staff" on public.staff;
drop policy if exists "admin_insert_staff" on public.staff;
drop policy if exists "admin_update_staff" on public.staff;
drop policy if exists "admin_delete_staff" on public.staff;

create policy "authenticated_select_staff"
  on public.staff
  for select
  to authenticated
  using (true);

create policy "admin_insert_staff"
  on public.staff
  for insert
  to authenticated
  with check (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  );

create policy "admin_update_staff"
  on public.staff
  for update
  to authenticated
  using (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  )
  with check (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  );

create policy "admin_delete_staff"
  on public.staff
  for delete
  to authenticated
  using (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  );

drop policy if exists "authenticated_select_staff_traits" on public.staff_traits;
drop policy if exists "admin_insert_staff_traits" on public.staff_traits;
drop policy if exists "admin_update_staff_traits" on public.staff_traits;
drop policy if exists "admin_delete_staff_traits" on public.staff_traits;

create policy "authenticated_select_staff_traits"
  on public.staff_traits
  for select
  to authenticated
  using (true);

create policy "admin_insert_staff_traits"
  on public.staff_traits
  for insert
  to authenticated
  with check (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  );

create policy "admin_update_staff_traits"
  on public.staff_traits
  for update
  to authenticated
  using (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  )
  with check (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  );

create policy "admin_delete_staff_traits"
  on public.staff_traits
  for delete
  to authenticated
  using (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  );

drop policy if exists "authenticated_select_staff_trait_assignments" on public.staff_trait_assignments;
drop policy if exists "admin_insert_staff_trait_assignments" on public.staff_trait_assignments;
drop policy if exists "admin_update_staff_trait_assignments" on public.staff_trait_assignments;
drop policy if exists "admin_delete_staff_trait_assignments" on public.staff_trait_assignments;

create policy "authenticated_select_staff_trait_assignments"
  on public.staff_trait_assignments
  for select
  to authenticated
  using (true);

create policy "admin_insert_staff_trait_assignments"
  on public.staff_trait_assignments
  for insert
  to authenticated
  with check (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  );

create policy "admin_update_staff_trait_assignments"
  on public.staff_trait_assignments
  for update
  to authenticated
  using (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  )
  with check (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  );

create policy "admin_delete_staff_trait_assignments"
  on public.staff_trait_assignments
  for delete
  to authenticated
  using (
    (current_setting('request.jwt.claims', true))::jsonb -> 'user_roles' ?| array['admin', 'super-admin']
  );

insert into public.staff (account_user_id, display_name, avatar_url)
select distinct up.user_id, coalesce(up."Username", 'Unnamed staff'), up.pfp_url
from public.user_profile up
join public.user_roles ur on ur.user_id = up.user_id
join public.roles r on r.id = ur.role_id
where r.name = 'staff'
on conflict (account_user_id) do update
set display_name = excluded.display_name,
    avatar_url = excluded.avatar_url,
    updated_at = now();

insert into public.staff (account_user_id, display_name, avatar_url)
select distinct up.user_id, coalesce(up."Username", 'Unnamed staff'), up.pfp_url
from public.mentor_groups mg
cross join lateral jsonb_array_elements_text(coalesce(mg.user_in_group, '[]'::jsonb)) as member(user_id)
join public.user_profile up on up.user_id = member.user_id::uuid
on conflict (account_user_id) do update
set display_name = excluded.display_name,
    avatar_url = excluded.avatar_url,
    updated_at = now();

insert into public.staff_traits (id, name, slug, description, metadata, is_active)
select mg.id,
       mg.group_name,
       lower(regexp_replace(mg.group_name, '[^a-zA-Z0-9]+', '-', 'g')),
       mg.description,
       '{}'::jsonb,
       true
from public.mentor_groups mg
on conflict (id) do update
set name = excluded.name,
    slug = excluded.slug,
    description = excluded.description;

select setval(
  pg_get_serial_sequence('public.staff_traits', 'id'),
  coalesce((select max(id) from public.staff_traits), 1),
  true
);

insert into public.staff_trait_assignments (staff_id, trait_id)
select distinct s.id, mg.id
from public.mentor_groups mg
cross join lateral jsonb_array_elements_text(coalesce(mg.user_in_group, '[]'::jsonb)) as member(user_id)
join public.staff s on s.account_user_id = member.user_id::uuid
on conflict (staff_id, trait_id) do nothing;