export const ANIMAL_ICONS = [
  { id: 'bat', name: { en: 'Bat', de: 'Fledermaus' } },
  { id: 'bear-face', name: { en: 'Bear Face', de: 'Bärengesicht' } },
  { id: 'bear', name: { en: 'Bear', de: 'Bär' } },
  { id: 'bee', name: { en: 'Bee', de: 'Biene' } },
  { id: 'cat', name: { en: 'Cat', de: 'Katze' } },
  { id: 'cat2', name: { en: 'Cat 2', de: 'Katze 2' } },
  { id: 'chameleon', name: { en: 'Chameleon', de: 'Chamäleon' } },
  { id: 'chick', name: { en: 'Chick', de: 'Küken' } },
  { id: 'chicken', name: { en: 'Chicken', de: 'Huhn' } },
  { id: 'clown-fish', name: { en: 'Clown Fish', de: 'Clownfisch' } },
  { id: 'crab', name: { en: 'Crab', de: 'Krabbe' } },
  { id: 'dino', name: { en: 'Dinosaur', de: 'Dinosaurier' } },
  { id: 'dolphin', name: { en: 'Dolphin', de: 'Delfin' } },
  { id: 'ducky', name: { en: 'Duck', de: 'Ente' } },
  { id: 'elephant', name: { en: 'Elephant', de: 'Elefant' } },
  { id: 'elephant2', name: { en: 'Elephant 2', de: 'Elefant 2' } },
  { id: 'fox', name: { en: 'Fox', de: 'Fuchs' } },
  { id: 'frog', name: { en: 'Frog', de: 'Frosch' } },
  { id: 'giraffe', name: { en: 'Giraffe', de: 'Giraffe' } },
  { id: 'goose', name: { en: 'Goose', de: 'Gans' } },
  { id: 'hedgehog', name: { en: 'Hedgehog', de: 'Igel' } },
  { id: 'hen', name: { en: 'Hen', de: 'Henne' } },
  { id: 'horse', name: { en: 'Horse', de: 'Pferd' } },
  { id: 'lion', name: { en: 'Lion', de: 'Löwe' } },
  { id: 'mouse', name: { en: 'Mouse', de: 'Maus' } },
  { id: 'mouse2', name: { en: 'Mouse 2', de: 'Maus 2' } },
  { id: 'mouse3', name: { en: 'Mouse 3', de: 'Maus 3' } },
  { id: 'owl', name: { en: 'Owl', de: 'Eule' } },
  { id: 'penguin', name: { en: 'Penguin', de: 'Pinguin' } },
  { id: 'pig', name: { en: 'Pig', de: 'Schwein' } },
  { id: 'rabbit', name: { en: 'Rabbit', de: 'Hase' } },
  { id: 'rabbit2', name: { en: 'Rabbit 2', de: 'Hase 2' } },
  { id: 'sea-turtle', name: { en: 'Sea Turtle', de: 'Meeresschildkröte' } },
];